"$schema" = 'https://starship.rs/config-schema.json'

[kubernetes]
disabled = true

[python]
disabled = true

[os]
disabled = false

[lua]
detect_files = [ ".lua-version", "!init.lua" ]

[gcloud]
disabled = true
